version: '3.8'

services:
  config-service:
    build: .
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql+asyncpg://cashup:cashup123@postgres:5432/cashup_config
      - REDIS_URL=redis://redis:6379/3
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py
    networks:
      - cashup-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=cashup_config
      - POSTGRES_USER=cashup
      - POSTGRES_PASSWORD=cashup123
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cashup-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    networks:
      - cashup-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # 可选：Redis管理界面
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - cashup-network
    restart: unless-stopped

  # 可选：PostgreSQL管理界面
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@cashup.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - cashup-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  cashup-network:
    driver: bridge