version: '3.8'

services:
  # PostgreSQL 数据库 - 生产环境
  postgres:
    image: postgres:15
    container_name: cashup_postgres_prod
    environment:
      POSTGRES_DB: cashup
      POSTGRES_USER: cashup
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cashup}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - cashup_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cashup"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存 - 生产环境
  redis:
    image: redis:7-alpine
    container_name: cashup_redis_prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - cashup_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # 核心服务 - 生产环境
  core-service:
    build:
      context: ./core-service
      dockerfile: Dockerfile
    container_name: cashup_core_prod
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql+asyncpg://cashup:cashup@postgres:5432/cashup
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - DEBUG=false
      - ALLOWED_ORIGINS=https://cashup.com,https://www.cashup.com
      - TRADING_ENGINE_URL=http://trading-engine:8002
      - STRATEGY_PLATFORM_URL=http://strategy-platform:8003
      - NOTIFICATION_URL=http://notification-service:8004
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./core-service:/app
      - ./configs:/app/configs
    restart: unless-stopped
    networks:
      - cashup_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 交易引擎 - 生产环境
  trading-engine:
    build:
      context: ./trading-engine
      dockerfile: Dockerfile
    container_name: cashup_trading_prod
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql+asyncpg://cashup:cashup@postgres:5432/cashup
      - REDIS_URL=redis://redis:6379/0
      - CORE_SERVICE_URL=http://core-service:8001
      - DEBUG=false
      - ALLOWED_ORIGINS=https://cashup.com,https://www.cashup.com
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      core-service:
        condition: service_healthy
    volumes:
      - ./trading-engine:/app
      - ./configs:/app/configs
    restart: unless-stopped
    networks:
      - cashup_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 策略平台 - 生产环境
  strategy-platform:
    build:
      context: ./strategy-platform
      dockerfile: Dockerfile
    container_name: cashup_strategy_prod
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql+asyncpg://cashup:cashup@postgres:5432/cashup
      - REDIS_URL=redis://redis:6379/0
      - CORE_SERVICE_URL=http://core-service:8001
      - TRADING_ENGINE_URL=http://trading-engine:8002
      - DEBUG=false
      - ALLOWED_ORIGINS=https://cashup.com,https://www.cashup.com
      - PYTHONPATH=/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      core-service:
        condition: service_healthy
      trading-engine:
        condition: service_healthy
    volumes:
      - ./strategy-platform:/app
      - ./strategies:/app/strategies
      - ./configs:/app/configs
    restart: unless-stopped
    networks:
      - cashup_network
    command: uvicorn main:app --host 0.0.0.0 --port 8003
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 通知服务 - 生产环境
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: cashup_notification_prod
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql+asyncpg://cashup:cashup@postgres:5432/cashup
      - REDIS_URL=redis://redis:6379/0
      - CORE_SERVICE_URL=http://core-service:8001
      - DEBUG=false
      - ALLOWED_ORIGINS=https://cashup.com,https://www.cashup.com
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      core-service:
        condition: service_healthy
    volumes:
      - ./notification-service:/app
      - ./configs:/app/configs
    restart: unless-stopped
    networks:
      - cashup_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 前端应用 - 生产环境
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cashup_frontend_prod
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8001/api/v1
      - REACT_APP_TRADING_URL=http://localhost:8002/api/v1
      - REACT_APP_STRATEGY_URL=http://localhost:8003/api/v1
      - REACT_APP_NOTIFICATION_URL=http://localhost:8004/api/v1
    depends_on:
      core-service:
        condition: service_healthy
      trading-engine:
        condition: service_healthy
      strategy-platform:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cashup_network

  # Nginx 反向代理 - 生产环境
  nginx:
    image: nginx:alpine
    container_name: cashup_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - core-service
      - trading-engine
      - strategy-platform
      - notification-service
      - frontend
    restart: unless-stopped
    networks:
      - cashup_network

volumes:
  postgres_data:
  redis_data:

networks:
  cashup_network:
    driver: bridge